# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='user_status',
            field=models.CharField(default='NOT_DECIDED_YET', max_length=20),
            preserve_default=False,
        ),
    ]
