# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
