# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20190129_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kotournament',
            old_name='tournament_status',
            new_name='status',
        ),
    ]
