# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
