# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='KoTournament',
        ),
    ]
