# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20190204_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_status',
            field=models.CharField(default=b'NOT_DECIDED_YET', max_length=20),
        ),
    ]
