# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190130_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='start_date_time',
            new_name='start_datetime',
        ),
    ]
