# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190130_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotournament',
            name='name',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kotournament',
            name='status',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
    ]
