# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_usertournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertournament',
            name='tournament_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertournament',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
