# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190129_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='CAN_JOIN', max_length=20),
            preserve_default=False,
        ),
    ]
