# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190130_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.User')),
            ],
        ),
    ]
