# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='name_1', max_length=50),
            preserve_default=False,
        ),
    ]
