# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
