# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotournament',
            name='t_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
