# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
            ],
        ),
    ]
