# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190130_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotournament',
            name='status',
            field=models.CharField(default=b'CAN_JOIN', max_length=30),
        ),
    ]
