# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-31 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='Dummy', max_length=20),
            preserve_default=False,
        ),
    ]
