# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournamentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentuser',
            name='tournament_id',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentuser',
            name='user_id',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
    ]
