# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20190130_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentuser',
            old_name='tournament_id',
            new_name='t_id',
        ),
    ]
