# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20190130_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=20)),
                ('player_one', models.CharField(max_length=20)),
                ('player_two', models.CharField(max_length=20)),
            ],
        ),
    ]
