# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-03 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20190203_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match_status',
            field=models.CharField(default=b'YET_TO_START', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player_one_match_status',
            field=models.CharField(default=b'YET_TO_START', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player_two_match_status',
            field=models.CharField(default=b'YET_TO_START', max_length=20),
        ),
    ]
