# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20190203_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player_one_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
