# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournamentmatch_player_one_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player_one_score',
            field=models.IntegerField(default=0),
        ),
    ]
