# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_auto_20190204_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player_two_score',
            field=models.IntegerField(default=0),
        ),
    ]
