# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_tournamentmatch_player_two_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner_user_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
