# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_tournamentmatch_winner_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player_one_submit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player_two_submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
