# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_auto_20190206_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentuser',
            name='current_round_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
