# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatch',
            name='score',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
