# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_usermatch_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatch',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
