# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20190202_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertournament',
            name='status',
            field=models.CharField(default='ALIVE', max_length=20),
            preserve_default=False,
        ),
    ]
