# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_rounds',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
