# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0005_tournamentplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.Tournament'),
            preserve_default=False,
        ),
    ]
