# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0006_auto_20190130_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set([('tournament', 'player')]),
        ),
    ]
