# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0008_tournamentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.Tournament'),
            preserve_default=False,
        ),
    ]
