# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0010_tmplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmplayer',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='tmplayer',
            name='tournament_match_id',
        ),
        migrations.AddField(
            model_name='tmplayer',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmplayer',
            name='tournament_match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.TournamentMatch'),
            preserve_default=False,
        ),
    ]
