# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0011_auto_20190202_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmplayer',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
