# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0012_tmplayer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmplayer',
            name='status',
            field=models.CharField(default=b'YET_TO_START', max_length=50),
        ),
    ]
