# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0013_auto_20190202_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tmplayer',
            unique_together=set([('player', 'tournament_match')]),
        ),
    ]
