# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0014_auto_20190202_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmplayer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
