# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0015_tmplayer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner_id',
            field=models.IntegerField(default=-1),
        ),
    ]
