# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0016_tournamentmatch_winner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.Player'),
        ),
    ]
