# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0017_auto_20190202_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmplayer',
            name='completed_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
