# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0019_tournamentmatch_round_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmplayer',
            name='tournament_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_tournament.TournamentMatch'),
        ),
    ]
