# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tournament', '0022_tournament_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='curr_round_no',
            field=models.IntegerField(default=1),
        ),
    ]
