# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(max_length=125)),
                ('amount', models.FloatField()),
                ('transaction_status', models.CharField(max_length=125)),
                ('transaction_datetime', models.DateTimeField()),
                ('franchise_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
