# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-15 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayreport',
            name='payment_report_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='displayreport',
            name='payment_report_reference_no',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='displayreport',
            name='sale_report_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='displayreport',
            name='sale_report_reference_no',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
