# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_reports', '0002_auto_20190515_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayreport',
            name='status',
        ),
        migrations.AddField(
            model_name='displayreport',
            name='sent_to_franchise_team',
            field=models.BooleanField(default=False),
        ),
    ]
