# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-15 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_reports', '0003_auto_20190515_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayreport',
            name='status',
            field=models.CharField(default='MATCHED', max_length=125),
            preserve_default=False,
        ),
    ]
